### ISSUE TITLE
Light and Color

### ISSUE THREAD

**Issue by ezileicorreia** [x2048/colored_torches#1]
Test this feature in lava and fire to see how it looks and put it on YouTube please!

**Comment by x2048** [comment]
There is a YT video showing particle effects here: https://www.youtube.com/watch?v=z1PERXV3adw. Is it something you wanted to see?

**Comment by ezileicorreia** [comment]
I think the fake colored torches could make up for the lack of colored lighting in Minetest, like in lava and fire!

**Comment by x2048** [comment]
Do you want to colored particles to lava and fire nodes in MTG?

**Comment by ezileicorreia** [comment]
I looked here, it doesn't work as I thought, thanks for your attention, I'll keep looking.

**Comment by x2048** [comment]
The video shows a bit more that this mod. Would you like the features in the video as mods?

**Comment by ezileicorreia** [comment]
I didn't find code in Lua that could be used in a point lights mod, but I made a feature request. Thank you for your attention.
